services:
  vault:
    image: hashicorp/vault:1.19
    container_name: vault
    restart: unless-stopped
    environment:
      VAULT_ADDR: http://127.0.0.1:8200
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK
    volumes:
      - ./vault/data:/vault/data
      - ./vault/config:/vault/config
    command: vault server -config=/vault/config/vault.hcl